### ISSUE TITLE
Suggestion: rename or alias fireImmediately to fireOnStart

### ISSUE THREAD

**Issue by elieven** [justinmahar/react-use-precision-timer#14]
I think the naming of the options `startImmediately` and `fireImmediately` may cause confusion. A more clear name for the option that sets the callback to **fire immediately** upon **timer start** could be `fireOnStart` or `fireImmediatelyOnStart`. This is a small detail, but worth considering.

**Comment by justinmahar** [comment]
Great suggestion. It would be an API breaking change though, so not sure it's worth breaking the code of everyone using this by changing it. If I make any other major changes to the library, this will definitely go along with them.

**Comment by justinmahar** [comment]
Done. Great suggestion.

**Comment by elieven** [comment]
Lovely <3

------- Original Message -------
