### ISSUE TITLE
Set clock speed 

### ISSUE THREAD

**Issue by sobocinski** [justinmahar/react-use-precision-timer#16]
Hi,
I have a question, is it possible to set the clock speed, if I want to speed up the clock, e.g. x2, or slow down to 0.25?

BTW, great library, you got a coffee from me.

**Comment by justinmahar** [comment]
Hey @sobocinski! I really appreciate the coffee, thanks a bunch. 🔥

Hmm so if I'm understanding what you're looking to do, you'd like to modulate how quickly the timer fires? 

My first thought is to create multiplier state outside the hook and multiply the inverse of that by the delay before passing it in. So 1x = `1/1 * delay`, 2x = `1/2 * delay`, 0.5x = `1/0.5 * delay`, etc. That should do it.

Here's an example:

```ts
const defaultDelay = 1000;
const [speed, setSpeed] = React.useState(1);
const callback = React.useCallback(() => console.log('Boom'), []);
// Calculate delay using speed
const delay = React.useMemo(() => speed > 0 ? defaultDelay * (1 / speed) : 1, [defaultDelay, speed]);
// The callback will be called every 1000 milliseconds.
const timer = useTimer({ delay, callback);
```

In this example, `speed` would be the multiplier, and we could set this to anything greater than 0 to make the timer fire faster, with 1 being "normal" speed determined by `defaultDelay`. 

Thoughts?

**Comment by justinmahar** [comment]
@sobocinski Loved this idea so much I've already added official support. 

Check out the [speed multiplier in the demo](https://justinmahar.github.io/react-use-precision-timer/?path=/story/docs-demo--page)!

To use this, pass a `speedMultiplier` option with the amount to multiply by. So `0.25` for 25% slower, or `2` for 2x faster.

To get speed multiplier support:

```
npm i react-use-precision-timer@latest
```

**Comment by sobocinski** [comment]
@justinmahar that's not quite what I meant 😉 but this parameter `speedMultiplier` also can be useful for someone. 

I wanted to be able, to set the speed of the "main" time/clock. I'm presenting time by getting `timer.getElapsedRunningTime()` 

A concrete example, I have a timeline graph that has play, pause and the ability to set the speed, e.g. to play in slow motion.
If it is possible to add a parameter, for example `timerSpeed: 2`, and it would realistically take a second and `timer.getElapsedRunningTime()` would return 2s. It would be wonderful.

Theoretically, I could do this, by multiply `timer.getElapsedRunningTime() * speed` , but when I will add the possibility to manipulate this speed in real time, I would probably quickly have different results.

**Comment by justinmahar** [comment]
Ah, I see. So you want to scale the times reported by the timer? Not sure how I'd add this to the library. I could add a scale option I suppose. I'd say for now, declare a scale or speed state and multiply the timer's output.
