### ISSUE TITLE
Recommended pattern for re-rendering elapsed time?

### ISSUE THREAD

**Issue by rileyjshaw** [justinmahar/react-use-precision-timer#18]
Hi @justinmahar, thanks for the library! Now that [the hook doesn’t trigger re-renders](https://github.com/justinmahar/react-use-precision-timer/issues/12) by default, do you have a recommendation for how to trigger re-renders? Initially, I hoped the following would work:

```.js
import { useStopwatch } from 'react-use-precision-timer';

function App() {
	const stopwatch = useStopwatch();
	return <div>{stopwatch.getElapsedRunningTime()}</div>;
}

export default App;
```

But the view doesn’t re-render. That led me to [this issue,](https://github.com/justinmahar/react-use-precision-timer/issues/12) so I tried to make the app re-render with some more explicit state:

```.js
import { useCallback, useMemo, useRef, useState } from 'react';
import { useTimer } from 'react-use-precision-timer';

function App() {
	const stopwatchRef = useRef(null);

	const [elapsedTime, setElapsedTime] = useState(0);
	const options = useMemo(
		() => ({
			delay: 0,
			runOnce: false,
			fireOnStart: false,
			startImmediately: true,
		}),
		[]
	);
	const cb = useCallback(() => {
		setElapsedTime(stopwatchRef.current.getElapsedRunningTime());
	}, []);

	const stopwatch = useTimer(options, cb);
	stopwatchRef.current = stopwatch;

	return <div>{elapsedTime}</div>;
}

export default App;
```

…but even this isn’t working. As far as I can tell, the callback is never run.

I feel like I must be missing something obvious here. Any advice?

**Comment by justinmahar** [comment]
Hey @rileyjshaw! Great question. So when you're using the stopwatch, there's no "tick" or anything, it just tracks start, pause, resume, and stop times. 

You'll want to create a timer "tick" yourself to trigger a re-render and update the UI. 

You can have it tick at any rate you'd like. In the [demo](https://justinmahar.github.io/react-use-precision-timer/?path=/story/docs-demo--page), this is exactly what I'm doing with the "render every X ms" setting to show the current values from the timer over time.

So to accomplish this, do something like:

```jsx
const stopwatch = useStopwatch();

// Re-render callback and timer
const renderEveryMillis = 10;
const [renderTime, setRenderTime] = useState(0);
const renderCallback = useCallback(() => setRenderTime(Date.now()), []);
const renderTimer = new Timer({ delay: renderEveryMillis }, renderCallback);

return <div>{stopwatch.getElapsedRunningTime()}</div>;
```

So you'll have the stopwatch keeping track of elapsed time, and a timer that triggers a re-render by changing some React state every so often. Makes sense?

**Comment by justinmahar** [comment]
Also in your code, the callback is never run because you specific a delay of `0`. This effectively turns the timer into a stopwatch. See the [delay prop in the docs here](https://justinmahar.github.io/react-use-precision-timer/?path=/story/docs-usetimer--page#timeroptions).

Give the approach I suggested a shot and see if that solves your problem!

**Comment by rileyjshaw** [comment]
I see. So on the following line:

```.js
const renderCallback = useCallback(() => setRenderTime(Date.now()), []);
```

the state could really be set to anything new:

```.js
const renderCallback = useCallback(() => setRenderTime(Math.random()), []);
```

---

Forcing a re-render every 10 milliseconds, regardless of whether `getElapsedRunningTime` has changed, feels like a hack to me. I understand if rendering elapsed time is outside of the scope of this library. But if it’s a use case you wish to support, I think there’s a strong case for a configuration flag:

```.js
const options = useMemo(() => ({
	runOnce: false,
	startImmediately: true,
	triggerRerender: true,
}));
const stopwatch = useTimer(options, cb);
```

Please feel free to close this issue if you don’t think it’s an important use case. Cheers!
