### ISSUE TITLE
How do you render the elapsed time? 

### ISSUE THREAD

**Issue by aronsonben** [justinmahar/react-use-precision-timer#21]
Hi, I know this isn't an issue but I'm not sure where else to ask this.

In the [live demo](https://justinmahar.github.io/react-use-precision-timer/?path=/story/docs-demo--page&globals=backgrounds.grid:true), the elapsed and started time are being displayed without issue. 

<img width="455" alt="image" src="https://github.com/justinmahar/react-use-precision-timer/assets/25832803/e33c0435-0238-4c54-9bb0-aff2f33e4b1a">

How is this happening? I am calling timer.getElapsedRunnignTime() in my code in the same manner as seen in the [useTimerExample](https://github.com/justinmahar/react-use-precision-timer/blob/master/src/components/UseTimerExample.tsx) component, yet I am receiving no updates. I don't see any effects being used on these components specifically.

Could someone please help point me in the right direction here?

**Comment by justinmahar** [comment]
Hey @aronsonben! Maybe explaining things a bit will help. So this timer hook operates entirely on unix timestamps and timeouts. If it's being used as a stopwatch, no timeouts are used. That means there's no timer tick that runs to trigger a React render to update the value on the page. It's up to you to handle rendering at whatever interval you desire.

In the demo, you will see that I have a separate render delay that's being used. Think of that as a frame rate that's showing you what's happening inside the timer every so often. By default it's set to 10ms, so every 10ms the page will be updated with the latest data from the timer.

The code you'll want to use in your component to trigger a render at a desired frame rate would be something like this:

```js
const [, setRenderTime] = React.useState(Date.now());
const frameRate = 10; // In millis
React.useEffect(() => {
  const timeout = setTimeout(() => setRenderTime(Date.now()), frameRate);
  return () => clearTimeout(timeout);
});
```

Does that make sense? Hopefully this solves your issue -- let me know!

**Comment by aronsonben** [comment]
Thanks for the reply @justinmahar. So if this is the case, will the entire component housing the timer/stopwatch be re-rendered every 10ms by default? So if this is the case, would keeping the stopwatch in it's own component be advised so your larger components with unrelated data are not being re-rendered every 10ms?

In my case, I am fetching some data to populate a table upon load. If I keep my stopwatch within the same component, then it appears that I will be fetching that data every 10ms as well. Is my assumption correct?

**Comment by justinmahar** [comment]
@aronsonben Sounds like you're on the right track. I'd definitely pass the stopwatch as a prop into a component that renders the time to prevent re-rendering the larger components outside of it. 

However, in React, fetching data usually takes place inside a `useEffect` function. So unless you're fetching data on every render (which would be bad!) then you should be good either way. Still, I agree that it's good practice to isolate frequent renders to a subcomponent, like you suggested.

**Comment by justinmahar** [comment]
Note- I updated the code block I provided above to use setInterval() instead of setTimeout().

**Comment by justinmahar** [comment]
@aronsonben You've inspired me to create an official solution for this, so I've added a `TimerRenderer` component to this library. See the [Timer Renderer](https://github.com/justinmahar/react-use-precision-timer#timer-renderer) section in the README.

This does exactly what we just discussed -- it will render a timer or stopwatch at regular intervals.

---

```jsx
import { TimerRenderer } from './TimerRenderer';
```

```jsx
const myTimer = useTimer(...); // Or useStopwatch()
```

```jsx
<TimerRenderer
  timer={myTimer}
  render={(t) => <>{t.getElapsedRunningTime()}</>}
  renderRate={10} // In milliseconds
/>
```

---

To get the latest version and try it out:

```bash
npm i react-use-precision-timer@latest
```

Let me know how it works out!

**Comment by aronsonben** [comment]
Oh cool, that's great @justinmahar! Thanks for the support. Let me give this a try.

**Comment by justinmahar** [comment]
@aronsonben No prob! Just made a few additional tweaks and updates -- `npm i react-use-precision-timer@latest`
