### ISSUE TITLE
What's the benefit?

### ISSUE THREAD

**Issue by jonas-pietzsch** [justinmahar/react-use-precision-timer#9]
Hey! This library looks interesting and the documentation is nice, too. Thanks.
May I ask one question; what's the advantage of your hooks over a simple timer implementation using only `setInterval`, `React.useEffect` and a bit of state?

We have a simple (countdown) timer in our React Native app that shows how long something is still reserved. It counts down seconds. Really simple implementation. But someones one can observe that it counts down 2 seconds at once, probably to catch up on another run being slightly too late. But accurate enough to switch off the representation of the reserved item at the target time because a time stamp is used for the "ultimate countdown target".
I wonder whether your hooks would fix that (yeah, I can simply try that out), looked into your libraries code and was a bit surprised to see quite some rocket science going on.

Thanks in advance

**Comment by justinmahar** [comment]
Hey @jverhoelen!

For something like a simple countdown timer, this library could be a bit overkill. I'm tracking fire times, elapsed times, and pause/resume times, which would never be used. On the other hand, it's really convenient to have a timer, stopwatch, and delay hook on hand at all times.

A few other things: simple setInterval calls will wander over time, and lack accuracy. This library will prevent that. It also has built-in functions for pausing and resuming, which are important features in some applications.

The benefits of using this library over a simple intervals and state are:
- Perfect mean accuracy with no wandering, with sub 10ms callback precision.
- Doesn't choke under pressure. Resilient to expensive callbacks and low timer delays.
- Can be used as a timer, one-time delay, or stopwatch.
- Supports pausing, and tracks cumulative elapsed pause time between resumes.
- Includes getters for everything

Check out the [demo](https://justinmahar.github.io/react-use-precision-timer/?path=/story/docs-demo--page) for what's baked in.

That's my best answer for you! I'd say simpler is better, but if you find the features this library offers important (including the convenience), then I'd say it's worth it. 

Cheers!
